import type { Metadata } from "next";
import { Cairo } from "next/font/google";
import "./globals.css";
import { Header } from "@/app/_components/header";
import { Footer } from "@/app/_components/footer";


const cairo = Cairo({
  variable: "--Cairo",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"]
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${cairo.variable} antialiased`}
      >
        <div className="h-[100vh] flex flex-col justify-between">
          <div>
            <Header />
            {children}
          </div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
